import Head from "next/head";
import { useState } from "react";
import MainContent from "../components/main-content/MainContent";
import NoteCard from "../components/NoteCard";
import Sidebar from "../components/sidebar/Sidebar";
import { Note } from "../utils/types";

export default function Home() {
  const testNotes: Note[] = [
    {
      title: "title1",
      description: "description1 what a heavy description",
      id: "1",
    },
    { title: "title2", description: "description2", id: "2" },
    { title: "title3", description: "description3", id: "3" },
  ];

  const [currentNoteId, setCurrentNoteId] = useState<null | string>(null);

  const defaultNote: Note = {
    title: "",
    description: "",
    id: "",
  };
  const [currentNote, setCurrentNote] = useState<Note>(defaultNote);

  function onSelectNote(id: string) {
    setCurrentNoteId(id);
    setCurrentNote((prev) => testNotes.filter((item) => item.id === id)[0]);
  }

  return (
    <div>
      <Head>
        <title>DNoteBook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}

      {/* Body */}
      <div className="flex">
        <Sidebar
          allNotes={testNotes}
          onSelectNote={onSelectNote}
          currentNoteId={currentNoteId}
        />
        <MainContent {...currentNote} />
      </div>
      {/* Footer */}
    </div>
  );
}
