import Head from "next/head";
import Router, { useRouter } from "next/router";
import { useEffect, useState } from "react";
import MainContent from "../components/main-content/MainContent";
import NoteCard from "../components/NoteCard";
import Sidebar from "../components/sidebar/Sidebar";
import { useAuthContext } from "../context/AuthContext";
import { Note } from "../utils/types";

export default function Home() {
  const { isLoggedIn, userDetails, logout } = useAuthContext();
  const router = useRouter();

  useEffect(() => {
    //if user is not Logged in then redirect user to Login page
    if (!isLoggedIn) {
      router.push("/auth/login");
    } else {
      router.push("/notes");
    }
  }, [isLoggedIn]);

  return (
    <div>
      <Head>
        <title>DNoteBook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text-xl text-white">Dashboard {userDetails?.name}</div>
      <p className="text-white">{userDetails?.email}</p>
      <button className="bg-orange-500" onClick={logout}>
        Logout
      </button>
    </div>
  );
}
